### ISSUE TITLE
libva error on Chromebook

### ISSUE THREAD

**Issue by lordsteve** [xurei/hyperkeys#30]
**Environment**
- Operating system: Chromebook Linux Crostini
- Hyperkeys version: 1.2.3

**Describe the bug and how to reproduce**
Trying to run AppImage...
`./HyperKeys.AppImage`
 ...produces following output:
`getPath /tmp/.mount_HyperKX9qt29/hyperkeys
getDataPath /home/lordsteve/.config/hyperkeys
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
/tmp/.mount_HyperKX9qt29/resources/app/300x300.png`
And then it just hangs until ctrl+C

**Expected behavior**
I expect the app to run

**Config file**
none found

Searching around a bit I did discover it may have something to do with Crostini being within a virtual environment that doesn't recognize the GPU properly, but that's about as far as my knowledge goes.

**Comment by xurei** [comment]
Can yo utry tu run the app with the `--disable-gpu-sandbox` flag ?

./HyperKeys.AppImage --disable-gpu-sandbox

**Comment by lordsteve** [comment]
That made the error go away, but it still hangs after the 300x300.png line, so maybe it didn't have anything to do with libva ¯\_(ツ)_/¯
